name: Deploy app

on:
    workflow_dispatch:

permissions:
    contents: read
    id-token: write

jobs:
    login:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v7

            - name: Sign in to Azure
              uses: azure/login@v2
              with:
                  client-id: ${{ vars.AZURE_CLIENT_ID}}
                  tenant-id: ${{ vars.AZURE_TENANT_ID}}
                  subscription-id: ${{vars.AZURE_SUBSCRIPTION_ID}}

            - name: Build and push image
              env:
                  ACR_NAME: ${{ vars.ACR_NAME }}
              run: |
                  set -euo pipefail
                  IMAGE_TAG="${GITHUB_SHA:0:7}"
                  IMAGE="${ACR_NAME}.azurecr.io/aca-app:${IMAGE_TAG}"

                  docker build -t "$IMAGE" ./app
                  az acr login --name "$ACR_NAME"
                  docker push "$IMAGE"

            - name: Update App Configuration and Container App
              env:
                  ACR_NAME: ${{ vars.ACR_NAME }}
                  APPCONFIG_NAME: ${{ vars.APPCONFIG_NAME }}
                  CONTAINER_APP_NAME: ${{ vars.CONTAINER_APP_NAME }}
                  AZURE_RESOURCE_GROUP: ${{ vars.AZURE_RESOURCE_GROUP }}

              run: |
                  set -euo pipefail
                  IMAGE_TAG="${GITHUB_SHA:0:7}"
                  IMAGE="${ACR_NAME}.azurecr.io/aca-app:${IMAGE_TAG}"

                  az appconfig kv set \
                    --name "$APPCONFIG_NAME" \
                    --key "app:imageTag" \
                    --label dev \
                    --value "$IMAGE_TAG" \
                    --auth-mode login \
                    --yes \
                    --output none

                  az containerapp update \
                    --name "$CONTAINER_APP_NAME" \
                    --resource-group "$AZURE_RESOURCE_GROUP" \
                    --image "$IMAGE" \
                    --output none
